### ISSUE TITLE
Bug with Stutter "Average SV"

### ISSUE THREAD

**Issue by IceDynamix** [Eve-ning/reamber#14]
## General Description

When trying to change the average SV with stutter, you'll have to change the threshold value before being able to input an initial SV above 1.

## Recreation

>Input any number above 1 in initial SV
>Change the Average SV
>Initial SV is locked to 0.1 - 1
>To unlock you need to change the threshold value

![amber_2018-09-04_03-58-39](https://user-images.githubusercontent.com/22303902/45005972-d7139300-aff6-11e8-93a6-d25c3853ebe0.png)

Edit: Just saw that you dropped Amber. Kinda sad to see but I guess that's how it goes. I was glad you made it though!

**Comment by Eve-ning** [comment]
yea this is a weird bug that I couldn't fix, I'll leave it open just so I can reference if I ever make another one

**Comment by Eve-ning** [comment]
```QDoubleSpinBox::valueChanged()``` of the stutter function now triggers ```private: stutter_limit_update()```
