### ISSUE TITLE
Automatic copying of output into clipboard on generate

### ISSUE THREAD

**Issue by IceDynamix** [Eve-ning/reamber#23]
When generating a function, making the output being automatically copied into the clipboard, ready for pasting into the .osu file, would save the trouble of having to CTRL+A/CTRL+C.

A settings menu where this can be toggled would be a nice addition, for those who fear of overwriting their clipboard by accident.

**Comment by Eve-ning** [comment]
Added feature. Will be on the look-out for any unintended behavior, closed.
