### ISSUE TITLE
This application failed to start because no Qt platform plugin could be initialized.

### ISSUE THREAD

**Issue by dephea** [Eve-ning/reamber#27]
"This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem."
no idea if it's problem on my end or not

**Comment by Eve-ning** [comment]
sorry, I missed out some dlls during release, should be ok now:
redl here
https://github.com/Eve-ning/reamber/releases/tag/v0.1.0-alpha

**Comment by Eve-ning** [comment]
I assume the issue is resolved, reopen/reply if it persists.
