### ISSUE TITLE
Copying one pattern to multiple objects at once (Copier)

### ISSUE THREAD

**Issue by IceDynamix** [Eve-ning/reamber#29]
Being able to copy one pattern of timing points to multiple objects at once would take out a lot of repitition in copy and pasting. Seperating each hitobject with a line break should do the trick.

Example: Complicated 2-point-function, being copied to multiple objects.

Current workflow: 
Create 2-p-f and paste in Copier
Repeat following for each object:
- Copy one single hitobject
- Paste in Copier
- Generate
- Paste in .osu

New workflow: 

Copy all the hitobjects you want the pattern copied to
Paste in Copier by linebreak (example:
01:56:826 (116826|2) - 
01:57:026 (117026|3) - 
Generate
Paste in .osu ONCE instead once for each object

**Comment by Eve-ning** [comment]
it already works if i get what you mean, just copy more than 1 hitobject at once from the editor and input in copier

01:57:026 (117026|3, \<more objects\>)

**Comment by Eve-ning** [comment]
also, separate note, but you can paste the timing points directly to the editor instead of the .osu. F6 in editor and just paste into the window

**Comment by Eve-ning** [comment]
Close on inactivity
