### ISSUE TITLE
2-point-function sv range

### ISSUE THREAD

**Issue by IceDynamix** [Eve-ning/reamber#31]
It should be possible to set initial_sv and end_sv to 0.01 instead of just 0.1.

**Comment by Eve-ning** [comment]
Does 0.01 work now? I avoided anything below 0.1 since those values didn't work from what I know

**Comment by Eve-ning** [comment]
May be valid if the editor supports it some day, i'll label this low priority for now

**Comment by IceDynamix** [comment]
I mean it does now

**Comment by Eve-ning** [comment]
Ok will see when I reach that stage

**Comment by Eve-ning** [comment]
Fixed 3b949aa29c59eff75e1888b83bf5763e3eb43c5e
