### ISSUE TITLE
2-point bezier (n-point bezier)

### ISSUE THREAD

**Issue by IceDynamix** [Eve-ning/reamber#34]
This should feel better and more intuitive than using normal cubic or sine, since you can control it to always finish in a fixed time at a fixed distance (it will always travel 1.0x if no other factor is involved). Due to the limitations of osu!, using negative control point coordinates is not possible. It's possible to expand to n-point bezier in case you're feeling excited, though I personally don't see any use for it.

Resources:
- https://cubic-bezier.com
- https://geeksforgeeks.org/cubic-bezier-curve-implementation-in-c/
- [My own bezier tool in Google Sheets](https://docs.google.com/spreadsheets/d/1bu15jSno3SxT5_7yOUkwudBRl-ktCi7sRI72tfdE0h4/), I used a lazy approach by calculating the position of 10000 intermediate points and calculating the velocity by subtraction.

**Comment by Eve-ning** [comment]
very interesting, i'll see about replacing some TPF stuff with this
