### ISSUE TITLE
Unable to Extract Release 0.2.0 Alpha

### ISSUE THREAD

**Issue by BrokenGale** [Eve-ning/reamber#48]
I am unable to extract the release zip file for Amber.
Is there something I am doing wrong or is the file corrupted in some way?

Affected system OS: Pop_OS 20.04 LTS
Reproducible on: Windows 10

**Comment by Eve-ning** [comment]
not sure what's the fix, I've uploaded 0.2.0a separately
[amber_v0.2.0.zip](https://github.com/Eve-ning/reamber/files/4916533/amber_v0.2.0.zip)
